services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=bid_auction
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=bid_postgres
    volumes:
      -  ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_DB: bid_notification
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysqldb:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8085:80
    environment:
      - PMA_ARBITRARY = 1
      - PMA_HOST:mysql
      - MYSQL_USERNAME:root
      - MYSQL_ROOT_PASSWORD:secret
    depends_on:
      - mysql
    networks:
      - spring
  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - spring
  auction:
    image: phuchnguyen99/bid_auction:latest
    container_name: bid_auction
    ports:
      - "8081:8081"
    networks:
      - spring
    depends_on:
      - postgres
      - rabbitmq
      - eurekaserver
  bids:
    image: phuchnguyen99/bid_bids:latest
    container_name: bid_bids
    ports:
      - "8080:8080"
    depends_on:
      - notification
      - client
      - eurekaserver
      - auction
    networks:
      - spring
  notification:
    image: phuchnguyen99/bid_notification:latest
    container_name: bid_notification
    ports:
      - "8083:8083"
    depends_on:
      - client
      - rabbitmq
      - eurekaserver
    networks:
      - spring
  eurekaserver:
    image: phuchnguyen99/bid_eurekaserver:latest
    container_name: bid_eurekaserver
    ports:
      - "8761:8761"
    networks:
      - spring
  client:
    image: phuchnguyen99/bid_client:latest
    container_name: bid_client
    ports:
      - "8080:8080"
    networks:
      - spring
networks:
  spring:
    driver: bridge
  postgres:
    driver: bridge
volumes:
  postgres:
  phpadmin:
  pgadmin:
  mysqldb: