server:
  port: 8083
spring:
  application:
    name: notification
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/biddb
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
  rabbitmq:
    exchange:
      internal: internal.exchange
    queue:
      notification: queue.notification
    routing-keys:
      internal-notification: internal.notification.routing-key
  kafka:
    bootstrap-servers: broker:9092